# Generated by Django 4.2.19 on 2025-02-08 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique_for_date='date')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('published', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('lead', models.TextField()),
                ('allow_comments', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='blog.category')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='core.image')),
            ],
            options={
                'ordering': ('-date',),
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
                ('author_url', models.URLField(blank=True, null=True)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comment', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('admin_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
        ),
    ]
