# Generated by Django 4.2.19 on 2025-02-08 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('begun', models.DateField()),
                ('completed', models.DateField(blank=True, null=True)),
                ('client', models.CharField(max_length=200)),
                ('public', models.BooleanField(default=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('short_lead', models.CharField(max_length=200)),
                ('images', models.ManyToManyField(related_name='projects', to='core.image')),
                ('languages', models.ManyToManyField(related_name='used_in', to='portfolio.language')),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='core.image')),
            ],
            options={
                'ordering': ('-completed',),
                'get_latest_by': 'completed',
            },
        ),
    ]
